// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfHIcDp73DmjlvAu-U5laopiJL5E2mt-g',
    appId: '1:456276418686:web:8cabc09f1afd4cafd9782f',
    messagingSenderId: '456276418686',
    projectId: 'workoutapplication-8d582',
    authDomain: 'workoutapplication-8d582.firebaseapp.com',
    storageBucket: 'workoutapplication-8d582.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoMKgXfF6Tko1Ed31JNejlGSTb2MCHUSw',
    appId: '1:456276418686:android:6d4fe84e8a8ed30cd9782f',
    messagingSenderId: '456276418686',
    projectId: 'workoutapplication-8d582',
    storageBucket: 'workoutapplication-8d582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALylKYKxb-rbXyifkp8fd4ZY_OSPGFC84',
    appId: '1:456276418686:ios:eac167eaeed35247d9782f',
    messagingSenderId: '456276418686',
    projectId: 'workoutapplication-8d582',
    storageBucket: 'workoutapplication-8d582.firebasestorage.app',
    iosBundleId: 'com.example.workoutpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALylKYKxb-rbXyifkp8fd4ZY_OSPGFC84',
    appId: '1:456276418686:ios:eac167eaeed35247d9782f',
    messagingSenderId: '456276418686',
    projectId: 'workoutapplication-8d582',
    storageBucket: 'workoutapplication-8d582.firebasestorage.app',
    iosBundleId: 'com.example.workoutpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfHIcDp73DmjlvAu-U5laopiJL5E2mt-g',
    appId: '1:456276418686:web:c76790072c91be39d9782f',
    messagingSenderId: '456276418686',
    projectId: 'workoutapplication-8d582',
    authDomain: 'workoutapplication-8d582.firebaseapp.com',
    storageBucket: 'workoutapplication-8d582.firebasestorage.app',
  );
}
